### ISSUE TITLE
Spurious warnings about 'anonymous' and 'named' flags when experiment uses neither

### ISSUE THREAD

**Issue by PeterJCLaw** [prophile/jacquard#101]
I've an experiment definition which looks like this:
``` yaml
id: some_test
name: Test of something
constraints:
  required_tags:
    - user
branches:
  - id: control
    settings:
      eligible_for_something: false
  - id: test
    settings:
      eligible_for_something: true
```

When I run `jacquard show experiment --settings some_test` I get the following warnings:
```
.../__init__.py:98: UserWarning: The `anonymous` flag no longer has any effect.
  warnings.warn("The `anonymous` flag no longer has any effect.")
.../__init__.py:101: UserWarning: The `named` flag no longer has any effect.
  warnings.warn("The `named` flag no longer has any effect.")
```

A similar experiment which has a different set of required tags (i.e: not `user`) does not exhibit this behaviour.

I think I do have other experiments loaded which do use the offending flags, however as noted I don't get the warnings when querying for non-user experiments, so I'm not convinced that that's the cause.
